---

- name: Provision Vagrant
  hosts: all
  tasks:
      - name: Say Hello
        debug: msg="Hello Ansible"

      - name: Update Apt Cache
        apt: update_cache=yes
        become: true

      - name: Upgrade Packages
        apt: upgrade=full
        become: true

      - name: Install System Utilities
        apt: 
          pkg:
            - ca-certificates
            - apt-transport-https 
            - lsb-release
            - curl
            - git
            - net-tools
            - python3
            - vim
            - unzip
            - zsh
        become: true

       name: Install PHP
        apt: update_cache=yes
          pkg:
            - php7.4
            - php7.4
            - php7.4-bcmath
            - php7.4-bz2
            - php7.4-cgi
            - php7.4-cli
            - php7.4-common
            - php7.4-curl
            - php7.4-fpm
            - php7.4-gd
            - php7.4-gmp
            - php7.4-imap
            - php7.4-json
            - php7.4-mysql
            - php7.4-mbstring
            - php7.4-opcache
            - php7.4-pgsql
            - php7.4-phpdbg
            - php7.4-zip  
        become: true

      - name: Install Apache
        become: true
        apt:
          pkg:
            apache2

      - name: Install Mysql
        become: true
        apt:
          pkg:
            - mysql-server
            - mysql-client

      - name: Cleanup unnecessary Packages
        apt: 
          autoremove: yes
        become: true
           
      - name: Say Done
        debug: msg="LAMP Packages Installed"
...
