---
- name: create non-root user
  group:
    name: "deployers"
    state: present
  become: true

- name: create non-root user
  user:
    name: "deployer"
    group: "deployers"
    shell: "/bin/bash"
    state: present
  become: true

- name: add authorized_key to non-root user
  authorized_key:
    user: deployer
    state: present
    key: "{{ lookup('file', '/Users/timrob/code/lamp_ansible/vagrant.pub') }}"
  become: true
...
